### ISSUE TITLE
Loot Chest generated through Recurrent Complex load empty.

### ISSUE THREAD

**Issue by Berstarke** [Ivorforce/YeGamolChattels#13]
Whenever I generate a Loot Chest through Recurrent Complex' structures, the game throws a NullPointerException both when generating and confirming an operation. The game doesn't crash, but the chest is generated without its contents.

Log: http://pastebin.com/7gtWuUFL

More specifically, the stacktraces themselves:

``` Java
[23:32:27] [Client thread/ERROR] [FML]: A TileEntity ygcLootChest(ivorius.yegamolchattels.blocks.TileEntityLootChest) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
    at ivorius.yegamolchattels.blocks.TileEntityLootChest.func_70299_a(TileEntityLootChest.java:329) ~[TileEntityLootChest.class:?]
    at ivorius.yegamolchattels.blocks.TileEntityLootChest.addLoot(TileEntityLootChest.java:65) ~[TileEntityLootChest.class:?]
    at ivorius.yegamolchattels.blocks.TileEntityLootChest.func_145839_a(TileEntityLootChest.java:217) ~[TileEntityLootChest.class:?]
    at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
    at ivorius.reccomplex.structures.MCRegistrySpecial.loadTileEntity(MCRegistrySpecial.java:124) [MCRegistrySpecial.class:?]
    at ivorius.reccomplex.structures.MCRegistrySpecial$ItemHidingRegistry.loadTileEntity(MCRegistrySpecial.java:222) [MCRegistrySpecial$ItemHidingRegistry.class:?]
    at ivorius.ivtoolkit.tools.IvWorldData.<init>(IvWorldData.java:102) [IvWorldData.class:?]
    at ivorius.reccomplex.structures.generic.GenericStructureInfo.constructWorldData(GenericStructureInfo.java:284) [GenericStructureInfo.class:?]
    at ivorius.reccomplex.structures.OperationGenerateStructure.renderPreview(OperationGenerateStructure.java:123) [OperationGenerateStructure.class:?]
    at ivorius.reccomplex.events.RCForgeEventHandler.onDrawWorld(RCForgeEventHandler.java:124) [RCForgeEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_555_RCForgeEventHandler_onDrawWorld_RenderWorldLastEvent.invoke(.dynamic) [?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:261) [ForgeHooksClient.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1354) [blt.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011) [blt.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[23:32:28] [Server thread/INFO]: Saving and pausing game...
[23:32:28] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiIngameMenu
[23:32:28] [Server thread/INFO]: Saving chunks for level 'Structure World'/Overworld
[23:32:28] [Server thread/INFO]: Saving chunks for level 'Structure World'/Nether
[23:32:28] [Server thread/INFO]: Saving chunks for level 'Structure World'/Dungeon
[23:32:28] [Server thread/INFO]: Saving chunks for level 'Structure World'/The Last Millenium
[23:32:28] [Server thread/INFO]: Saving chunks for level 'Structure World'/SpectreWorld
[23:32:28] [Server thread/INFO]: Saving chunks for level 'Structure World'/Pocket Plane
[23:32:37] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiChat
[23:32:47] [Client thread/INFO]: [CHAT] /#copy, /#confirm
[23:32:47] [Client thread/INFO]: [CHAT] /#copy, /#confirm
[23:32:50] [Server thread/ERROR] [FML]: A TileEntity ygcLootChest(ivorius.yegamolchattels.blocks.TileEntityLootChest) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
    at ivorius.yegamolchattels.blocks.TileEntityLootChest.func_70299_a(TileEntityLootChest.java:329) ~[TileEntityLootChest.class:?]
    at ivorius.yegamolchattels.blocks.TileEntityLootChest.addLoot(TileEntityLootChest.java:65) ~[TileEntityLootChest.class:?]
    at ivorius.yegamolchattels.blocks.TileEntityLootChest.func_145839_a(TileEntityLootChest.java:217) ~[TileEntityLootChest.class:?]
    at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
    at ivorius.reccomplex.structures.MCRegistrySpecial.loadTileEntity(MCRegistrySpecial.java:124) [MCRegistrySpecial.class:?]
    at ivorius.reccomplex.structures.MCRegistrySpecial$ItemHidingRegistry.loadTileEntity(MCRegistrySpecial.java:222) [MCRegistrySpecial$ItemHidingRegistry.class:?]
    at ivorius.ivtoolkit.tools.IvWorldData.<init>(IvWorldData.java:102) [IvWorldData.class:?]
    at ivorius.reccomplex.structures.generic.GenericStructureInfo.constructWorldData(GenericStructureInfo.java:284) [GenericStructureInfo.class:?]
    at ivorius.reccomplex.structures.generic.GenericStructureInfo.prepareInstanceData(GenericStructureInfo.java:241) [GenericStructureInfo.class:?]
    at ivorius.reccomplex.structures.generic.GenericStructureInfo.prepareInstanceData(GenericStructureInfo.java:56) [GenericStructureInfo.class:?]
    at ivorius.reccomplex.worldgen.StructureGenerator.instantly(StructureGenerator.java:93) [StructureGenerator.class:?]
    at ivorius.reccomplex.structures.OperationGenerateStructure.perform(OperationGenerateStructure.java:74) [OperationGenerateStructure.class:?]
    at ivorius.reccomplex.entities.StructureEntityInfo.performOperation(StructureEntityInfo.java:137) [StructureEntityInfo.class:?]
    at ivorius.reccomplex.commands.CommandConfirm.func_71515_b(CommandConfirm.java:42) [CommandConfirm.class:?]
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[23:32:50] [Server thread/ERROR] [FML]: A TileEntity ygcLootChest(ivorius.yegamolchattels.blocks.TileEntityLootChest) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
    at ivorius.yegamolchattels.blocks.TileEntityLootChest.func_70299_a(TileEntityLootChest.java:329) ~[TileEntityLootChest.class:?]
    at ivorius.yegamolchattels.blocks.TileEntityLootChest.addLoot(TileEntityLootChest.java:65) ~[TileEntityLootChest.class:?]
    at ivorius.yegamolchattels.blocks.TileEntityLootChest.func_145839_a(TileEntityLootChest.java:217) ~[TileEntityLootChest.class:?]
    at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
    at ivorius.reccomplex.structures.MCRegistrySpecial.loadTileEntity(MCRegistrySpecial.java:124) [MCRegistrySpecial.class:?]
    at ivorius.reccomplex.structures.MCRegistrySpecial$ItemHidingRegistry.loadTileEntity(MCRegistrySpecial.java:222) [MCRegistrySpecial$ItemHidingRegistry.class:?]
    at ivorius.ivtoolkit.tools.IvWorldData.<init>(IvWorldData.java:102) [IvWorldData.class:?]
    at ivorius.reccomplex.structures.generic.GenericStructureInfo.constructWorldData(GenericStructureInfo.java:284) [GenericStructureInfo.class:?]
    at ivorius.reccomplex.structures.generic.GenericStructureInfo.generate(GenericStructureInfo.java:123) [GenericStructureInfo.class:?]
    at ivorius.reccomplex.structures.generic.GenericStructureInfo.generate(GenericStructureInfo.java:56) [GenericStructureInfo.class:?]
    at ivorius.reccomplex.worldgen.StructureGenerator.instantly(StructureGenerator.java:93) [StructureGenerator.class:?]
    at ivorius.reccomplex.structures.OperationGenerateStructure.perform(OperationGenerateStructure.java:74) [OperationGenerateStructure.class:?]
    at ivorius.reccomplex.entities.StructureEntityInfo.performOperation(StructureEntityInfo.java:137) [StructureEntityInfo.class:?]
    at ivorius.reccomplex.commands.CommandConfirm.func_71515_b(CommandConfirm.java:42) [CommandConfirm.class:?]
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

```

The structure itself seems to generate just fine. Here's the worlddata NBT for a simple structure of a loot chest filled with wooden planks.

![2015-11-18 13_04_19-nbtexplorer](https://cloud.githubusercontent.com/assets/13529919/11244661/df59b3d0-8df5-11e5-94f2-cd953abc01ce.png)

---

Yes, it was me on the IRC. Should've posted this here earlier.

**Comment by PublicVoidUpdate** [comment]
Same problem on SRP Calamity, im just a player so I don't have any clue how they are managing their things, but i did notice its random when it does or doesn't generate loot, and often other inventories (like iron chests) work fine. I am running cleanroom and calamity is 1.12.2 so that might have something to do with it, but i have no clue.
