### ISSUE TITLE
[compatability] Duplicate stat id: entity.ygcGhost

### ISSUE THREAD

**Issue by Dulciphi** [Ivorforce/YeGamolChattels#6]
Hello, This is just for your info. I've passed this on to Silentine as well.

I went to test the Grimoire of Gaia spawns in a modded environment tonight and got this

---- Minecraft Crash Report ----
// Don't do that.

Time: 14/03/15 06:44
Description: Exception in server tick loop

java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.ygcGhost.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.ygcGhost.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}" at id stat.killEntity.ygcGhost
    at net.minecraft.stats.StatBase.func_75971_g(SourceFile:42)
    at net.minecraft.stats.StatList.func_151182_a(StatList.java:212)
    at net.minecraft.entity.EntityList$EntityEggInfo.<init>(EntityList.java:320)
    at gaia.item.ItemGaiaSpawnEgg.registerEntityEgg(ItemGaiaSpawnEgg.java:49)
    at gaia.Gaia.load(Gaia.java:241)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Ivorforce** [comment]
What version were you testing this on, exactly? That is, both YGC and Grimoire of Gaia. There doesn't seem to be a 1.7 version of the mod...

**Comment by Dulciphi** [comment]
Pardon, I should've included that.
YeGamolChattels-1.1.1.1.
and the version of Grimoire of Gai is a beta test version, essentially - hence the error's been sent to Silentine. GoG version is Grim3212 Core-V0.2 - 1.7.10. It's been updated but has not yet been released.

**Comment by Ivorforce** [comment]
Ah, looking at the source code, it looks like an int ID conflict, but it's actually a bug on their end. I'll message the author to fix the bug :)

**Comment by Dulciphi** [comment]
:) thank you.
